spring:
  application:
    name: wikimedia.consumer

opensearch:
  index: wikimedia
  bulk-size: 100

kafka:
  bootstrap-server: localhost:9092
  group-id: wikimedia
  topic-name: wikimedia.recentchange
